### ISSUE TITLE
irdf - cat doesn't seem to be filled in record.py

### ISSUE THREAD

**Issue by PK0207** [varun-iyer/sdi_pipeline#14]
When running a script to create a database for PTF data, the error is as follows:
![image](https://user-images.githubusercontent.com/30590837/115130289-7072f600-9fa3-11eb-9ec2-87311dee5872.png)
The issues seems to be because the cat is not being loaded but I am not sure.

**Comment by varun-iyer** [comment]
Closed: data was not loaded properly
